DATABASE_SOURCE = "postgres://postgres:2020@localhost:5432/taskmanager?sslmode=disable"
SERVER_PORT = "8080"
JWT_SECRET = "thisisasecret"
JWT_ISSUER = "leapfrog"
EMAIL_SENDER = "###@gmail.com"
EMAIL_PASSWORD = "#####"
EMAIL_SERVER = "smtp.gmail.com"
EMAIL_SERVER_SMTP_PORT = "587"


